- name: RabbitMQ
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
    - role: role_common
    - role: role_cloud
    - role: rabbitmq
    - role: role_init_password
    - role: role_end
