
# Install RabbitMQ
- name: Install RabbitMQ on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# Set RabbitMQ

- name: Restart RabbitMQ
  shell: systemctl start rabbitmq-server

- name: Enable the management console of RabbitMQ
  shell: rabbitmq-plugins enable rabbitmq_management

- name: Create administrator for RabbitMQ console
  shell: |
    rabbitmqctl add_user admin admin
    rabbitmqctl set_user_tags admin administrator

- name: Restart RabbitMQ Server
  service:
    name: rabbitmq-server
    state: restarted
    enabled: yes
  
- block:
  - name: Check RabbitMQ Version
    shell: rabbitmqctl status | grep RabbitMQ*
    register: check_rabbitmq_version
    notify: check_rabbitmq_version

  - name: Check Erlang Version
    shell: systemctl status rabbitmq-server | grep /usr/lib
    register: check_erlang_version
    notify: check_erlang_version
